/*
 * This file is generated by jOOQ.
 */
package vn.team.system.repository.model;


import vn.team.system.repository.model.tables.Record;
import vn.team.system.repository.model.tables.Staff;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>Personel</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index RECORD_STAFFID = Indexes0.RECORD_STAFFID;
    public static final Index STAFF_DEPARTID = Indexes0.STAFF_DEPARTID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index RECORD_STAFFID = Internal.createIndex("StaffId", Record.RECORD, new OrderField[] { Record.RECORD.STAFFID }, false);
        public static Index STAFF_DEPARTID = Internal.createIndex("DepartId", Staff.STAFF, new OrderField[] { Staff.STAFF.DEPARTID }, false);
    }
}
