/*
 * This file is generated by jOOQ.
 */
package vn.team.system.repository.model;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import vn.team.system.repository.model.tables.Depart;
import vn.team.system.repository.model.tables.Record;
import vn.team.system.repository.model.tables.Staff;
import vn.team.system.repository.model.tables.User;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Personel extends SchemaImpl {

    private static final long serialVersionUID = -551939857;

    /**
     * The reference instance of <code>personel</code>
     */
    public static final Personel PERSONEL = new Personel();

    /**
     * The table <code>personel.depart</code>.
     */
    public final Depart DEPART = Depart.DEPART;

    /**
     * The table <code>personel.record</code>.
     */
    public final Record RECORD = Record.RECORD;

    /**
     * The table <code>personel.staff</code>.
     */
    public final Staff STAFF = Staff.STAFF;

    /**
     * The table <code>personel.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Personel() {
        super("personel", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Depart.DEPART,
            Record.RECORD,
            Staff.STAFF,
            User.USER);
    }
}
