/*
 * This file is generated by jOOQ.
 */
package vn.team.system.repository.model;


import vn.team.system.repository.model.tables.Depart;
import vn.team.system.repository.model.tables.Record;
import vn.team.system.repository.model.tables.Staff;
import vn.team.system.repository.model.tables.User;


/**
 * Convenience access to all tables in personel
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>personel.depart</code>.
     */
    public static final Depart DEPART = Depart.DEPART;

    /**
     * The table <code>personel.record</code>.
     */
    public static final Record RECORD = Record.RECORD;

    /**
     * The table <code>personel.staff</code>.
     */
    public static final Staff STAFF = Staff.STAFF;

    /**
     * The table <code>personel.user</code>.
     */
    public static final User USER = User.USER;
}
