/*
 * This file is generated by jOOQ.
 */
package vn.team.system.repository.model.routines;


import org.jooq.impl.AbstractRoutine;

import vn.team.system.repository.model.Personel;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Spgettop10staff extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -444629263;

    /**
     * Create a new routine call instance
     */
    public Spgettop10staff() {
        super("spGetTop10Staff", Personel.PERSONEL);
    }
}
