/*
 * This file is generated by jOOQ.
 */
package vn.team.system.repository.model.routines;


import vn.team.system.repository.model.Personel;

import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Spthongkethanhtichphongban extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1923707823;

    /**
     * Create a new routine call instance
     */
    public Spthongkethanhtichphongban() {
        super("spThongKeThanhTichPhongBan", Personel.PERSONEL);
    }
}
