/*
 * This file is generated by jOOQ.
 */
package vn.team.system.repository.model.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import vn.team.system.repository.model.Keys;
import vn.team.system.repository.model.Personel;
import vn.team.system.repository.model.tables.records.DepartRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Depart extends TableImpl<DepartRecord> {

    private static final long serialVersionUID = 626013162;

    /**
     * The reference instance of <code>personel.depart</code>
     */
    public static final Depart DEPART = new Depart();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DepartRecord> getRecordType() {
        return DepartRecord.class;
    }

    /**
     * The column <code>personel.depart.Id</code>.
     */
    public final TableField<DepartRecord, String> ID = createField(DSL.name("Id"), org.jooq.impl.SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>personel.depart.Name</code>.
     */
    public final TableField<DepartRecord, String> NAME = createField(DSL.name("Name"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * Create a <code>personel.depart</code> table reference
     */
    public Depart() {
        this(DSL.name("depart"), null);
    }

    /**
     * Create an aliased <code>personel.depart</code> table reference
     */
    public Depart(String alias) {
        this(DSL.name(alias), DEPART);
    }

    /**
     * Create an aliased <code>personel.depart</code> table reference
     */
    public Depart(Name alias) {
        this(alias, DEPART);
    }

    private Depart(Name alias, Table<DepartRecord> aliased) {
        this(alias, aliased, null);
    }

    private Depart(Name alias, Table<DepartRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Depart(Table<O> child, ForeignKey<O, DepartRecord> key) {
        super(child, key, DEPART);
    }

    @Override
    public Schema getSchema() {
        return Personel.PERSONEL;
    }

    @Override
    public UniqueKey<DepartRecord> getPrimaryKey() {
        return Keys.KEY_DEPART_PRIMARY;
    }

    @Override
    public List<UniqueKey<DepartRecord>> getKeys() {
        return Arrays.<UniqueKey<DepartRecord>>asList(Keys.KEY_DEPART_PRIMARY);
    }

    @Override
    public Depart as(String alias) {
        return new Depart(DSL.name(alias), this);
    }

    @Override
    public Depart as(Name alias) {
        return new Depart(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Depart rename(String name) {
        return new Depart(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Depart rename(Name name) {
        return new Depart(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
